package com.prslc.zhiflow.data.service

import com.prslc.zhiflow.core.network.Client
import com.prslc.zhiflow.core.network.safeApiCall
import com.prslc.zhiflow.data.model.MomentsFeedResponse
import com.prslc.zhiflow.data.model.MomentsResponse
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request

/**
 * Service handling moment-related API requests using OkHttp.
 */
class MomentService(private val okHttpClient: OkHttpClient) {

    /**
     * Fetches the publication history (posts, articles, answers) created by a specific user.
     *
     * This endpoint retrieves the aggregated creative works published by the user,
     * acting as the data source for the user's "Works/Posts" tab.
     *
     * @param urlToken The user's unique URL token identifier.
     * @param nextUrl The pagination URL provided by the previous response for infinite scrolling.
     * @return A [Result] containing [MomentsResponse] on success.
     */
    suspend fun getUserPosts(
        urlToken: String,
        nextUrl: String? = null
    ): Result<MomentsResponse> = okHttpClient.safeApiCall {
        val url = nextUrl ?: "${Client.BASE_URL}/moments/$urlToken/origin"

        Request.Builder()
            .url(url.toHttpUrl())
            .get()
            .build()
    }

    /**
     * Fetches the activity stream or timeline generated by a specific user.
     *
     * This serves as the data backing for the user's "Activities" tab, capturing
     * their publication history and public interactions.
     *
     * @param urlToken The user's unique URL token identifier.
     * @param nextUrl The pagination URL provided by the previous response for infinite scrolling.
     * @return A [Result] containing [MomentsFeedResponse] on success.
     */
    suspend fun getUserActivities(
        urlToken: String,
        nextUrl: String? = null
    ): Result<MomentsFeedResponse> = okHttpClient.safeApiCall {
        val url = nextUrl ?: "${Client.BASE_URL}/moments/$urlToken/activities"

        Request.Builder()
            .url(url.toHttpUrl())
            .get()
            .build()
    }

    /**
     * Fetches the upvoted content of a user.
     *
     * @param urlToken The user's unique URL token.
     * @param nextUrl The pagination URL provided by the previous response.
     * @return A [Result] containing [MomentsFeedResponse] on success.
     */
    suspend fun getUserVote(
        urlToken: String,
        nextUrl: String? = null
    ): Result<MomentsFeedResponse> = okHttpClient.safeApiCall {
        val url = nextUrl ?: "${Client.BASE_URL}/moments/$urlToken/vote"

        Request.Builder()
            .url(url.toHttpUrl())
            .get()
            .build()
    }
}
